preprocessing: &preprocessing_config
  universal_label: &universal_label
    - 'sedentary_sitting_other' 
    # - 'sedentary_sitting_transport' 
    - 'sedentary_lying'
    - 'upright_standing'
    - 'upright_stepping'
    # - 'cycling'
  extrasensory_preprocessor:
    in: 
      dir: datasets/extrasensory/
    out: 
      dir: datasets/preprocessed/extrasensory/
      suffix: activities_minutes.csv

    labels: [
      'label:LYING_DOWN',
      'label:SITTING',
      'label:OR_standing',
      'label:FIX_walking',
      'label:FIX_running',
      'label:BICYCLING',
      'label:IN_A_CAR'
    ]
    label_converter:
      # sedentary activities 
      sedentary_sitting_other: es__sitting 
      sedentary_sitting_transport: es__in_a_car
      sedentary_lying: es__lying_down
      
      # upright activities 
      upright_standing: es__standing 
      upright_stepping: es__walking

      # other 
      cycling: es__bicycling 


pretrain:
  model_type: "CL" # one of ["CL", "MTL"]
  universal_label: *universal_label
  preprocessing_config: *preprocessing_config

  # Model Related Config
  input_shape = 3 # number of input features: x,y,z


# specific experiment config:
experiment:
  # Data Preprocessing Related Config
  dataset: 
    - ES # one of ["ES", "SOME OTHER DATASET: TBD"]
  force_preprocess: false # if true, preprocess data again and overwrite existing files

  # Training Related Config
  training_epochs: &default_epochs 15
  output_directory: "./checkpoints"
  batch_size: 32


