preprocessing: &preprocessing_config
  universal_label: &universal_label
    - 'sedentary_sitting_other' 
    - 'sedentary_sitting_transport' 
    - 'sedentary_lying'
    - 'upright_standing'
    - 'upright_stepping'
    - 'cycling'
  extrasensory_preprocessor:
    in: 
      dir: datasets/extrasensory/
    out: 
      dir: datasets/preprocessed/extrasensory/
      suffix: activities_minutes.csv

    labels: [
      'label:LYING_DOWN',
      'label:SITTING',
      'label:OR_standing',
      'label:FIX_walking',
      'label:FIX_running',
      'label:BICYCLING',
      'label:IN_A_CAR'
    ]
    label_converter:
      # sedentary activities 
      sedentary_sitting_other: es__sitting 
      sedentary_sitting_transport: es__in_a_car
      sedentary_lying: es__lying_down
      
      # upright activities 
      upright_standing: es__standing 
      upright_stepping: es__walking

      # other 
      cycling: es__bicycling
  wisdm_preprocessor:
    in:
      dir: datasets/wisdm-dataset/raw/watch/
    out:
      save: true # wether to save the processed dataframe
      dir: datasets/preprocessed/wisdm/
    label:
      - A # walking
      - D # sitting
      - E # Standing
    label_converter: 
      # sedentary activities 
      D: sedentary_sitting_other
      # upright activities 
      E: upright_standing
      A: upright_stepping
    universal_label: *universal_label


pretrain: &pretrain
  universal_label: *universal_label
  preprocessing_config: *preprocessing_config
  # Data Preprocessing Related Config
  dataset: wisdm # extrasensory dataset

finetuning:
  universal_label: *universal_label
  preprocessing_config: *preprocessing_config
    # Data Preprocessing Related Config
  dataset: ES # wisdm dataset

# specific experiment config:
pretrain_exp:
  # experiment prefix/name will be will append to the output dir
  exp_name: "pretrain_mtl_ctl"
  force_preprocess: False # if true, preprocess data again and overwrite existing files

  # Training Related Config
  training_epochs: 25
  output_directory: "./checkpoints/"
  verbose: True # whether to explicitly print out training progress
  model_type: "mtl" # one of ["baseline","cl", "mtl"]
  batch_size: 8
  valid_raio: 0.1 # the portion of data to be used for validation
  learning_rate: 0.0001

  # debug # only run 100 training and validation samples
  debug: False
  load_weights: true
  weights_file: /home/siyuan/class/cmsc828a_finalproject/pre_traincheckpoints/pretrain_mtl/epoch-07.h5


finetuning_exp: 
  # experiment prefix/name will be will append to the output dir
  exp_name: "ft_cl"
  force_preprocess: True # if true, preprocess data again and overwrite existing files

  # Training Related Config
  training_epochs:  10
  output_directory: "./checkpoints"
  verbose: true # whether to explicitly print out training progress
  model_type: "cl" # one of ["baseline","cl", "mtl"]
  batch_size: 8
  valid_raio: 0.8 # the portion of data to be used for validation
  learning_rate: 0.00005

  load_weights: true
  weights_file: /fs/class-projects/spring2023/cmsc828a/c828ag04/CMSC828A_FinalProject/checkpoints/pretrain_cl/sedentary_sitting_other-upright_standing-upright_stepping/epoch-24-acc-0.3248-precision-0.3248-recall-0.3248.h5

  # debug # only run 100 training and validation samples
  debug: False


